name: R.E.Moyen Professional Profile
favicon: null
layout_spectrum: 0.49263
typography_spectrum: 0.90471
title: R.E.Moyen Professional Career Profile
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20232a'
    - '#757c8e'
    - '#393d49'
    - '#eeeeee'
    - '#b1b2b4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.12989117880351841
  rhythmicContrast: 0.9304976856801659
purpose: []
